### PR TITLE
Add parlparse id to 2010 mps

### LINKED ISSUE #143: add a parlparse ID for each 2010 candidate who was elected
This should be a Django management command, which:
* Goes through each constituency ...
* Finds any [members of parliament for the constituency starting at the 2010 election onwards](https://github.com/mysociety/parlparse/blob/master/members/all-members-2010.xml)
* Finds the corresponding person (or possibly "people" if the MP has changed in a [by-election](http://en.wikipedia.org/wiki/MPs_elected_in_the_United_Kingdom_general_election,_2010) and the new MP happens to be in the YourNextMP PopIt) in the YourNextMP PopIt instance
* Sets the parlparse person ID as a new identifier on the person in PopIt (the [people.xml](https://raw.githubusercontent.com/mysociety/parlparse/master/members/people.xml) file gives you the mapping between member IDs in [all-members-2010](https://github.com/mysociety/parlparse/blob/master/members/all-members-2010.xml) and person IDs)

### PR DESCRIPTION
**Pull request by chrismytton**
Iterate over all the MPs from the 2010 election and add their parlparse/publicwhip id as an identifier. This should make it easier to do #144.

Fixes #143

### CODE REVIEW

**Comment by mhl** [comment]
I think I'd prefer to add parlparse as a submodule (like `data/UK-Political-Parties`) rather than duplicating the data into this repository.

**Comment by mhl** [comment]
It worries me a bit that this just uses any unique result based on firstname + lastname that's found in PopIt - I think it would be worth checking that: `party_memberships['2010']` and `standing_in['2010']` match the parlparse member data. (We might miss some people from by-elections, but there are few enough of them that they can be done by hand.)

**Comment by tfgg** [comment]
firstname + lastname definitely won't fly, c.f. Tom Harris the lib dem candidate and Tom Harris the labour MP, matching by party and constituency should be more robust. We'll know if we miss people, anyway, since there should be 650 matches.

**Comment by chrismytton** [comment]
@mhl I've added the parlparse data as a submodule, as you suggested.

I've also added some extra checks for the data before adding the parlparse id in https://github.com/mysociety/yournextmp-popit/commit/6c695991c0a67968d23b13eaa6179b63bbb0bdba (which I'll squash/rebase properly before merging). However I was only able to use `standing_in['2010']` to check their constituency as there is quite a bit difference in the names of parties between YNMP and parlparse which makes it tricky to use `party_memberships['2010']`:

### YNMP

```
[
        "Labour Party",
        "Social Democratic Party",
        "UK Independence Party (UKIP)",
        "Liberal Democrats",
        "Green Party",
        "Conservative Party",
        "Independent",
        "Trade Unionist and Socialist Coalition",
        "British National Party",
        "Alliance - Alliance Party of Northern Ireland",
        "Pirate Party UK",
        "Sinn Féin",
        "English Democrats",
        "A Vote Against MP Expense Abuse",
        "Workers Revolutionary Party",
        "Socialist Labour Party",
        "Official Monster Raving Loony Party",
        "Lincolnshire Independents Lincolnshire First",
        "Scotland Against Crooked Lawyers",
        "The Respect Party",
        "Christian Party \"Proclaiming Christ's Lordship\"",
        "The Animal Protection Party",
        "All The South Party",
        "Christian Peoples Alliance",
        "Solihull and Meriden Residents Association",
        "City INDEPENDENTS",
        "Solidarity - Scotland's Socialist Movement",
        "National Front",
        "Traditional Unionist Voice - TUV",
        "Mebyon Kernow - The Party for Cornwall",
        "Plaid Cymru - The Party of Wales",
        "Medway Independent Party",
        "Scottish National Party (SNP)",
        "Scottish Green Party",
        "Socialist Alternative",
        "Independents Federation UK",
        "Communist Party of Britain",
        "Freedom and Responsibility",
        "Wessex Regionalists",
        "Unity For Peace And Socialism",
        "Democratic Labour Party",
        "SDLP (Social Democratic & Labour Party)",
        "United Voice",
        "Conservative and Unionist Party",
        "The Better Britain Party",
        "Hugh Salmon for Battersea Party",
        "Save King George Hospital",
        "Scottish Socialist Party",
        "Nationwide Reform Party",
        "Lewisham People Before Profit",
        "Anticapitalists - Workers Power",
        "Democratic Unionist Party - D.U.P.",
        "Equal Parenting Alliance",
        "The Peace Party - Non-violence, Justice, Environment",
        "Magna Carta Conservation Party Great Britain",
        "The New Party",
        "The Magna Carta Party",
        "Common Sense Party",
        "Best of a Bad Bunch",
        "New Millennium Bean Party",
        "Nobody Party",
        "Direct Democracy (Communist) Party",
        "Radical Reform Group",
        "Trust",
        "Impact Party",
        "Integrity UK",
        "Jannen will put Brent North First",
        "People Before Profit Alliance",
        "Movement for Active Democracy (M.A.D.)",
        "Communist League Election Campaign",
        "Fancy Dress Party",
        "Local Liberals People Before Politics Party",
        "Christian Movement for Great Britain",
        "Your Right To Democracy Party Limited",
        "Citizens for Undead Rights and Equality",
        "The Liberal Party",
        "Reduce Tax On Beer",
        "Independent Ealing Acton Communities Public Services",
        "Independents to Save Queen Mary's Hospital",
        "Blue Environment Party",
        "New Independent Conservative Chelsea and Fulham",
        "Reform 2000 Party",
        "Bushra Irfan of Blackburn",
        "Peoples Party Essex",
        "Money Reform Party",
        "The Youth Party",
        "Independent Voice for Halifax",
        "Democratic Nationalists",
        "You Party",
        "Socialist Equality Party",
        "The Science Party",
        "Northampton - Save Our Public Services",
        "Scrap Members Allowances",
        "The Scottish Jacobite Party",
        "Get Snouts Out The Trough",
        "Libertarian Party",
        "Independent Kidderminster Hospital and Health Concern",
        "Clause 28, Children's Protection Christian Democrats",
        "English Independence Party",
        "Campaign for Independent Politicians",
        "Middle England Party",
        "National Liberal Party, The Third Way",
        "INDEPENDENT Leave-the-EU Alliance",
        "Free Public Transport Party",
        "Humanity",
        "Tendring First",
        "Neath Port Talbot Independent Party",
        "Speaker seeking re-election",
        "The Cornish Democrats",
        "The True English (Poetry) Party",
        "The Justice & Anti-Corruption Party",
        "Animal Welfare Party",
        "Alliance For Green Socialism",
        "Cut The Deficit",
        "Alliance for Workers' Liberty",
        "Virtue Currency Cognitive Appraisal Party",
        "Cambridge Socialists",
        "Islam Zinda Baad Platform",
        "The P.N.D.P.",
        "The Socialist Party of Great Britain",
        "The Macclesfield Independent",
        "Justice Party",
        "The Joy of Talk",
        "Restoration Party",
        "Independent People Together",
        "Apolitical Democrats",
        "Common Good",
        "No Candidate Deserves My Vote!",
        "Bromsgrove Independent Conservative"
]
```

### Parlparse

```
In [9]: set([m['party'] for m in self.members])
Out[9]:
{'Alliance',
 'Con',
 'DUP',
 'Green',
 'Ind',
 'LDem',
 'Lab',
 'PC',
 'Res',
 'SDLP',
 'SF',
 'SNP',
 'SPK',
 'UKIP'}
```

**Comment by dracos** [comment]
Map:
'Alliance',        "Alliance - Alliance Party of Northern Ireland",
'Con',        "Conservative Party" or         "Conservative and Unionist Party" ***
'DUP',        "Democratic Unionist Party - D.U.P.",
'Green',        "Green Party",
'Ind',        "Independent",
'LDem',        "Liberal Democrats",
'Lab',        "Labour Party",
'PC',        "Plaid Cymru - The Party of Wales",
'Res',        "The Respect Party",
'SDLP',        "SDLP (Social Democratic & Labour Party)",
'SF',        "Sinn Féin",
'SNP',        "Scottish National Party (SNP)",
'SPK',        "Speaker seeking re-election",
'UKIP',         "UK Independence Party (UKIP)",

**Comment by chrismytton** [comment]
@dracos Ah that'll do the trick, thanks! Is there any way to distinguish between "Conservative Party" and "Conservative and Unionist Party" for "Con"?

**Comment by dracos** [comment]
The official name of the Conservative Party is the Conservative and Unionist Party. Looks like they use the latter in Northern Ireland, looking at the constituencies where it's been used, only a few. Anyway, they have no MPs, so doesn't matter, can be ignored.

**Pull request merged**
