### PR TITLE
Improve placement of logos on party pages on mobile

### PR DESCRIPTION
**Pull request by mhl**
Thanks to @zarino for help with this.

### CODE REVIEW

**Comment by zarino** [comment]
This is a good start. Out of interest, @mhl, how many parties have two logos? And do any have more than two?

**Comment by mhl** [comment]
@zarino 100 have 2 logos, 122 have 3, and none have more than that

Details here: https://gist.github.com/mhl/2960f7422da64bcfd868

**Comment by mhl** [comment]
(Though that's all the parties in the database, most of them aren't standing candidates.)

**Comment by zarino** [comment]
Ok, good to know. Thanks.

**Pull request merged**
