### PR TITLE
New profile page layout

### LINKED ISSUE #146: improve the design of the person view page
At the moment, the candidate view page is basically just looks like a table of data:

ynmp-people-view

I thought this was fine, since it suggests "here's a data source you can use" and we didn't necessarily want it to be a destination page to find out about candidates; however, various people have convinced me that this is wrong - we are very high in Google rankings for many candidate-related searches and it's missing an opportunity not providing an engaging page when people follow those links.

Hopefully this should be flexible enough to include links out to social media platforms we haven't included yet (e.g. linkedin, youtube) and potentially allow us to include past election leaflets from electionleaflets.org, etc.

### PR DESCRIPTION
**Pull request by zarino**
Fixes #146.

And partly addresses #138.

profile

### CODE REVIEW

**Comment by dracos** [comment]
Only thing I'd say is that given #142 it seems to make it even more prominent.

**Comment by tfgg** [comment]
Minor bikeshedding and probably for another time - but is the party too de-emphasized in this new design? It wasn't very prominent beforehand, and now it's quite hard to spot.

**Comment by mhl** [comment]
@zarino Great stuff :) Another thought I had about the gender is that we could have that in a "Demographics" section at the bottom, even if it's the only thing in it. (Although we could put date of birth in that section too.

One other thing, with reference to @tfgg's comment about the display party affiliation - we do have logos for many parties in PopIt, which we can make available to use in the template pretty easily. They're mostly black on a white background, I think, e.g.

* https://yournextmp.popit.mysociety.org/image-proxy/https%3A%2F%2Fyournextmp.popit.mysociety.org%2Forganizations%2Fimages%2F54bea4ae5a9c3744778f9b29%2Fparty%3A90/128/0

Liberal Democrat emblem

**Comment by struan** [comment]
I think the party definitely needs to be more prominent. I'd have assumed it would be in the description under the name - 'Green party candidate for Liverpool, Riverside'

**Comment by mhl** [comment]
I've moved the gender, added a demographics section, changed the wording about the data so it's not emphasizing that we're not offering CSV yet, and also made it more clear what the absence of information for 2010 / 2015 means:

new-profile

I haven't addressed the party prominence issue, but I'll create a new ticket for that, or edit https://github.com/mysociety/yournextmp-popit/issues/162

**Comment by JoeMitchell** [comment]
Looks lovely, well done both. 

Small thing:
- The categorisation of data seems a bit odd. A website / wikipedia page isn't really a Contact Detail. What do you think about recategorising these as: <ul><li>Personal Details,</li> <li>Constituency,</li><li>Contact Details,</li> <li>Web + Social links,</li> <li>Demographics</li>

Prioritisation of data in the page:
- Why do we appear to prioritise their DOB? Isn't having their age in Demographics enough? (Or is it a unique identifier thing?)
- If we work on the assumption that our audience here will tend to be editors adding info, or journos/v interested people (rather than members of the public who are likely to see YNMP data, but dressed up as BBC/Guardian etc)...what's the most important thing to them? I would suggest: Personal Details (Name); Party; Constituency; Email/Phone; Social (starting with Twitter)...

**Comment by andylolz** [comment]
This is looking awesome. V pleased to see you’ve addressed the “absence of information” thing, Mark!

> Why do we appear to prioritise their DOB? Isn't having their age in Demographics enough?

Agreed. I’d remove Personal details completely (since it’s just name & DOB, and name is already written above) and move DOB down to demographics, putting it in grey after their age.

**Comment by mhl** [comment]
Here's a new version taking into account some of those suggestions from @JoeMitchell and @andylolz and incorporating a party logo:

new-profile-view

(The party logo looks a bit silly when it's a thin and tall one, but I'm sure that'd take @zarino no time at all to fix ;))

**Comment by JoeMitchell** [comment]
Boom! I think that looks great. Nice one.

**Comment by andylolz** [comment]
Agree with Joe – This looks great.

btw I didn’t mention the sidebar before – I __really love__ the sidebar.

**Comment by symroe** [comment]
This is incredibly beautiful and exciting :)  Sorry I've not been involved before, and I have no useful input now apart from enthusiasm :)

**Pull request merged**
